// .repos/alchemy-effect/fixtures/nextjs/app/counter/counter.jsx
"use client";

import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <p data-testid="count">count:{count}</p>
      <button type="button" data-testid="increment" onClick={() => setCount((c) => c + 1)}>
        Increment
      </button>
    </div>
  );
}

// .repos/alchemy-effect/fixtures/solidstart/src/components/Counter.tsx
import { createSignal } from "solid-js";
// oxlint-disable-next-line import/no-unassigned-import
import "./Counter.css";

export default function Counter() {
  const [count, setCount] = createSignal(0);
  return (
    <button class="increment" onClick={() => setCount(count() + 1)} type="button">
      Clicks: {count()}
    </button>
  );
}
