// .repos/alchemy-effect/examples/aws-website-nuxt/app/pages/index.vue
<script setup lang="ts">
// Title lives on the page so the dev test's hot-reload marker rewrite
// targets this file.
useHead({ title: "Nuxt on AWS" });

// SSR reads the Lambda environment through the plain Node contract:
// `process.env`. `useState` serializes the server-read value into the
// payload so the client render matches.
const greeting = useState("greeting", () => {
  if (import.meta.server) {
    return typeof process.env.GREETING === "string"
      ? process.env.GREETING
      : "Hello!";
  }
  return "Hello!";
});
</script>

<template>
  <main>
    <h1 class="text-3xl font-bold">{{ greeting }}</h1>
    <Card
      title="Styled with Tailwind CSS"
      body="This card is a Vue component styled with Tailwind utilities."
    />
    <NuxtLink class="mt-4 inline-block underline" to="/about"
      >about (prerendered)</NuxtLink
    >
  </main>
</template>

// .repos/alchemy-effect/examples/aws-website-waku/src/pages/index.tsx
import { getEnv } from "waku";
import { Card } from "../components/Card.tsx";

export default async function HomePage() {
  // `getEnv` reads the server environment at request time — the portable
  // way to reach env values from RSC page modules. On AWS it is backed by
  // the Lambda's `process.env`.
  const greeting = getEnv("GREETING") ?? "Hello!";
  return (
    <div>
      <h1 className="text-3xl font-bold">{greeting}</h1>
      <Card
        title="Styled with Tailwind CSS"
        body="This card is a React component styled with Tailwind utilities."
      />
      <p className="mt-4 text-slate-600">
        This page is rendered by the server on every request.
      </p>
    </div>
  );
}

// Dynamic: rendered by the Lambda at request time.
export const getConfig = async () => ({ render: "dynamic" }) as const;
