// .repos/alchemy-effect/examples/aws-website-nextjs/app/components/Card.tsx
// A React component styled with Tailwind utility classes.
export function Card({ title, body }: { title: string; body: string }) {
  return (
    <div className="mt-6 max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 className="text-lg font-semibold">{title}</h2>
      <p className="mt-2 text-slate-600">{body}</p>
    </div>
  );
}

// .repos/alchemy-effect/examples/neon-website-nuxt/app/components/Card.vue
<script setup lang="ts">
// A Vue component styled with Tailwind utility classes.
defineProps<{ title: string; body: string }>();
</script>

<template>
  <div
    class="mt-6 max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-sm"
  >
    <h2 class="text-lg font-semibold">{{ title }}</h2>
    <p class="mt-2 text-slate-600">{{ body }}</p>
  </div>
</template>
